In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

from sklearn import preprocessing

## Load Data - Preprocessing

In [2]:
raw_data = pd.read_csv("D:/Data Science Tutorial/Data/Audiobooks_data.csv", header=None)
raw_data

0       1     2      3      4   5     6     7    8   9    10  11
0        873  2160.0  2160  10.13  10.13   0  8.91  0.00  0.0   0    0   1
1        611  1404.0  2808   6.66  13.33   1  6.50  0.00  0.0   0  182   1
2        705   324.0   324  10.13  10.13   1  9.00  0.00  0.0   1  334   1
3        391  1620.0  1620  15.31  15.31   0  9.00  0.00  0.0   0  183   1
4        819   432.0  1296   7.11  21.33   1  9.00  0.00  0.0   0    0   1
...      ...     ...   ...    ...    ...  ..   ...   ...  ...  ..  ...  ..
14079  27398  2160.0  2160   7.99   7.99   0  8.91  0.00  0.0   0   54   0
14080  28220  1620.0  1620   5.33   5.33   1  9.00  0.61  0.0   0    4   0
14081  28671  1080.0  1080   6.55   6.55   1  6.00  0.29  0.0   0   29   0
14082  31134  2160.0  2160   6.14   6.14   0  8.91  0.00  0.0   0    0   0
14083  32832  1620.0  1620   5.33   5.33   1  8.00  0.38  0.0   0   90   0

[14084 rows x 12 columns]

In [3]:
raw_data = raw_data.values
usefull_data = raw_data[:, 1:]

In [4]:
usefull_data
inputs_data = usefull_data[:, : -1]
targets_data = usefull_data[:, -1]

In [5]:
inputs_data, targets_data

(array([[2.160e+03, 2.160e+03, 1.013e+01, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        [1.404e+03, 2.808e+03, 6.660e+00, ..., 0.000e+00, 0.000e+00,
         1.820e+02],
        [3.240e+02, 3.240e+02, 1.013e+01, ..., 0.000e+00, 1.000e+00,
         3.340e+02],
        ...,
        [1.080e+03, 1.080e+03, 6.550e+00, ..., 0.000e+00, 0.000e+00,
         2.900e+01],
        [2.160e+03, 2.160e+03, 6.140e+00, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        [1.620e+03, 1.620e+03, 5.330e+00, ..., 0.000e+00, 0.000e+00,
         9.000e+01]]),
 array([1., 1., 1., ..., 0., 0., 0.]))

In [6]:
scaled_inputs = preprocessing.scale(inputs_data)
scaled_inputs, targets_data

(array([[ 1.12768719,  0.7351559 ,  0.61364906, ..., -0.44129834,
         -0.14873032, -0.70217541],
        [-0.37135283,  1.72474784, -0.08999108, ..., -0.44129834,
         -0.14873032,  1.36121133],
        [-2.51283858, -2.06868796,  0.61364906, ..., -0.44129834,
          1.96928571,  3.08447937],
        ...,
        [-1.01379856, -0.91416402, -0.11229667, ..., -0.44129834,
         -0.14873032, -0.37339401],
        [ 1.12768719,  0.7351559 , -0.19543571, ..., -0.44129834,
         -0.14873032, -0.70217541],
        [ 0.05694432, -0.08950406, -0.359686  , ..., -0.44129834,
         -0.14873032,  0.31818067]]),
 array([1., 1., 1., ..., 0., 0., 0.]))

### Balance dataset

In [7]:
sum_one = int(targets_data.sum())
sum_one
sum_zero = 0
remove_indices = []
for i in range(targets_data.shape[0]):
    if(targets_data[i] == 0):
        sum_zero += 1
        if(sum_zero > sum_one):
            remove_indices.append(i)
balanced_targets = np.delete(targets_data, remove_indices, axis = 0)
balanced_inputs = np.delete(inputs_data, remove_indices, axis = 0)
balanced_inputs.shape, balanced_targets.shape

((4474, 10), (4474,))

In [8]:
shuffle_indices = np.arange(balanced_targets.shape[0])
np.random.shuffle(shuffle_indices)

shuffle_inputs = scaled_inputs[shuffle_indices]
shuffle_targets = targets_data[shuffle_indices]

shuffle_inputs, shuffle_targets

(array([[ 1.12768719,  0.7351559 ,  0.27095401, ..., -0.44129834,
         -0.14873032, -0.70217541],
        [ 1.12768719,  0.7351559 , -0.359686  , ...,  2.29967159,
         -0.14873032,  1.00975534],
        [ 0.05694432, -0.08950406,  0.17970385, ..., -0.20015729,
         -0.14873032, -0.70217541],
        ...,
        [ 1.12768719,  0.7351559 , -0.359686  , ...,  2.29967159,
         -0.14873032,  2.01877413],
        [ 0.05694432, -0.08950406, -0.359686  , ..., -0.44129834,
         -0.14873032, -0.70217541],
        [-0.79964998, -0.74923203, -0.359686  , ...,  1.32706936,
         -0.14873032, -0.69083812]]),
 array([1., 0., 1., ..., 0., 1., 0.]))

In [9]:
train_num = int(0.8 * shuffle_targets.shape[0])
validation_num = int(0.1 * shuffle_targets.shape[0])
test_num = int(shuffle_targets.shape[0] - train_num - validation_num)
train_num, validation_num, test_num

(3579, 447, 448)

In [10]:
shuffle_inputs.shape, shuffle_targets.shape

((4474, 10), (4474,))

In [11]:
train_inputs = shuffle_inputs[:train_num, :]
train_targets = shuffle_targets[:train_num]
train_inputs, train_targets

(array([[ 1.12768719,  0.7351559 ,  0.27095401, ..., -0.44129834,
         -0.14873032, -0.70217541],
        [ 1.12768719,  0.7351559 , -0.359686  , ...,  2.29967159,
         -0.14873032,  1.00975534],
        [ 0.05694432, -0.08950406,  0.17970385, ..., -0.20015729,
         -0.14873032, -0.70217541],
        ...,
        [ 0.05694432, -0.08950406, -0.359686  , ...,  1.16630866,
         -0.14873032,  0.839696  ],
        [ 0.05694432, -0.08950406,  0.07223143, ...,  0.20174446,
         -0.14873032, -0.39606859],
        [ 0.59231575,  3.20913577,  0.18173163, ...,  0.04500278,
         -0.14873032,  0.51091459]]),
 array([1., 0., 1., ..., 0., 1., 1.]))

In [12]:
validation_inputs = shuffle_inputs[train_num:train_num + validation_num, :]
validation_targets = shuffle_targets[train_num: train_num + validation_num]
validation_inputs, validation_targets

(array([[-0.79964998, -0.74923203, -0.22382465, ..., -0.44129834,
         -0.14873032,  1.59929441],
        [ 1.12768719,  0.7351559 , -0.359686  , ...,  1.32706936,
         -0.14873032, -0.70217541],
        [ 1.12768719,  0.7351559 ,  0.56092674, ..., -0.44129834,
         -0.14873032, -0.70217541],
        ...,
        [-2.51283858, -2.06868796,  0.61364906, ..., -0.44129834,
         -0.14873032, -0.70217541],
        [ 1.12768719,  0.7351559 , -0.30290812, ..., -0.44129834,
         -0.14873032,  0.21614506],
        [-0.79964998, -0.74923203, -0.30290812, ...,  1.32706936,
         -0.14873032,  1.59929441]]),
 array([0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1.,
        1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0.,
        1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
        1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1

In [13]:
test_inputs = shuffle_inputs[train_num + validation_num:, :]
test_targets = shuffle_targets[train_num + validation_num:]
test_inputs, test_targets

(array([[ 0.05694432, -0.08950406,  0.18173163, ..., -0.44129834,
         -0.14873032, -0.30537027],
        [ 0.05694432, -0.08950406, -0.359686  , ...,  1.87767475,
         -0.14873032, -0.6001398 ],
        [-0.79964998, -0.74923203,  0.61364906, ..., -0.44129834,
         -0.14873032,  0.20480777],
        ...,
        [ 1.12768719,  0.7351559 , -0.359686  , ...,  2.29967159,
         -0.14873032,  2.01877413],
        [ 0.05694432, -0.08950406, -0.359686  , ..., -0.44129834,
         -0.14873032, -0.70217541],
        [-0.79964998, -0.74923203, -0.359686  , ...,  1.32706936,
         -0.14873032, -0.69083812]]),
 array([1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0.,
        0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
        1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1.,
        0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
        1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1

In [14]:
print("Number of one train: ", train_targets.sum(), ", percent: ", train_targets.sum() / train_num)
print("Number of one validation: ", validation_targets.sum(), ", percent: ", validation_targets.sum() / validation_num)
print("Number of one test: ", test_targets.sum(), ", percent: ", test_targets.sum() / test_num)

Number of one train:  1782.0 , percent:  0.4979044425817267
Number of one validation:  219.0 , percent:  0.4899328859060403
Number of one test:  236.0 , percent:  0.5267857142857143


In [15]:
np.savez("Audiobooks_train", inputs = train_inputs, targets = train_targets)
np.savez("Audiobooks_validation", inputs = validation_inputs, targets = validation_targets)
np.savez("Audiobooks_test", inputs = test_inputs, targets = test_targets)

In [16]:
train_data = np.load("Audiobooks_train.npz")
validation_data = np.load("Audiobooks_validation.npz")
test_data = np.load("Audiobooks_test.npz")

## Model

In [17]:
input_size = 10
output_size = 2
hidden_layer_size = 50

model = tf.keras.Sequential([
    tf.keras.layers.Dense(hidden_layer_size, activation="relu"),
    tf.keras.layers.Dense(hidden_layer_size, activation="relu"),
    tf.keras.layers.Dense(output_size, activation="softmax")
])

In [18]:
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [19]:
train_data["inputs"].astype(float)

array([[ 1.12768719,  0.7351559 ,  0.27095401, ..., -0.44129834,
        -0.14873032, -0.70217541],
       [ 1.12768719,  0.7351559 , -0.359686  , ...,  2.29967159,
        -0.14873032,  1.00975534],
       [ 0.05694432, -0.08950406,  0.17970385, ..., -0.20015729,
        -0.14873032, -0.70217541],
       ...,
       [ 0.05694432, -0.08950406, -0.359686  , ...,  1.16630866,
        -0.14873032,  0.839696  ],
       [ 0.05694432, -0.08950406,  0.07223143, ...,  0.20174446,
        -0.14873032, -0.39606859],
       [ 0.59231575,  3.20913577,  0.18173163, ...,  0.04500278,
        -0.14873032,  0.51091459]])

In [20]:
max_epoch = 100
batch_size = 100
early_stopping = tf.keras.callbacks.EarlyStopping(patience=2)

model.fit(
    train_data["inputs"].astype(float), 
    train_data["targets"].astype(int), 
    validation_data=(validation_data["inputs"].astype(float), validation_data["targets"].astype(float)), 
    batch_size=batch_size,
    epochs=max_epoch,
    callbacks=[early_stopping],
    verbose=2
)

Epoch 1/100
36/36 - 2s - loss: 0.5302 - accuracy: 0.7636 - val_loss: 0.4130 - val_accuracy: 0.8591 - 2s/epoch - 43ms/step
Epoch 2/100
36/36 - 0s - loss: 0.3802 - accuracy: 0.8664 - val_loss: 0.3551 - val_accuracy: 0.8635 - 149ms/epoch - 4ms/step
Epoch 3/100
36/36 - 0s - loss: 0.3356 - accuracy: 0.8785 - val_loss: 0.3236 - val_accuracy: 0.8837 - 136ms/epoch - 4ms/step
Epoch 4/100
36/36 - 0s - loss: 0.3149 - accuracy: 0.8854 - val_loss: 0.3088 - val_accuracy: 0.8770 - 156ms/epoch - 4ms/step
Epoch 5/100
36/36 - 0s - loss: 0.3018 - accuracy: 0.8899 - val_loss: 0.2995 - val_accuracy: 0.8859 - 151ms/epoch - 4ms/step
Epoch 6/100
36/36 - 0s - loss: 0.2908 - accuracy: 0.8921 - val_loss: 0.2875 - val_accuracy: 0.8859 - 185ms/epoch - 5ms/step
Epoch 7/100
36/36 - 0s - loss: 0.2828 - accuracy: 0.8947 - val_loss: 0.2869 - val_accuracy: 0.8859 - 173ms/epoch - 5ms/step
Epoch 8/100
36/36 - 0s - loss: 0.2766 - accuracy: 0.8952 - val_loss: 0.2786 - val_accuracy: 0.8949 - 149ms/epoch - 4ms/step
Epoch 9/10

In [21]:
test_loss, test_accuracy = model.evaluate(test_data["inputs"], test_data["targets"])

14/14 [==============================] - 0s 3ms/step - loss: 0.2569 - accuracy: 0.9040
